apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: $SITE_NAME
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: $SITE_NAME
      spec:
        containers:
        - image: $SITE_DOCKER_IMAGE:$SITE_DOCKER_TAG
          name: $SITE_NAME
          env:
          - name: MARIADB_HOST
            value: $DATABASE_NAME
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          volumeMounts:
          - mountPath: /$SITE_NAME/drupal
            name: $SITE_NAME-drupal-data
          - mountPath: /$SITE_NAME/apache
            name: $SITE_NAME-apache-data
          - mountPath: /$SITE_NAME/php
            name: $SITE_NAME-php-data
        restartPolicy: Always
        volumes:
        - name: $SITE_NAME-drupal-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-drupal-data
        - name: $SITE_NAME-apache-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-apache-data
        - name: $SITE_NAME-php-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-php-data
  status: {}
kind: List
metadata: {}