apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: $DATABASE_NAME
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: $DATABASE_NAME
      spec:
        containers:
        - env:
          - name: ALLOW_EMPTY_PASSWORD
            value: "yes"
          image: $DATABASE_DOCKER_IMAGE:$DATABASE_DOCKER_TAG
          name: $DATABASE_NAME
          resources: {}
          volumeMounts:
          - mountPath: /$SITE_NAME/mariadb
            name: $SITE_NAME-mariadb-data
        restartPolicy: Always
        volumes:
        - name: $SITE_NAME-mariadb-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-mariadb-data
  status: {}
kind: List
metadata: {}