apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: web
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: web
      spec:
        containers:
        - image: "docksal/web:2.1-apache2.4"
          name: web
          env:
          - name: APACHE_BASIC_AUTH_PASS
            value: null
          - name: APACHE_BASIC_AUTH_USER
            value: null
          - name: APACHE_DOCUMENTROOT
            value: '/var/www/docroot'
          ports:
          - containerPort: 80
          - containerPort: 443
          resources: {}
          volumeMounts:
          - mountPath: /var/www
            name: web
          - mountPath: /mnt/nfs
            name: nfs

        restartPolicy: Always
        volumes:
          - name: site-files
          - name: nfs
            persistentVolumeClaim:
              claimName: nvbenfs
  status: {}
kind: List
metadata: {}