apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    name: db
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: db
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: default
          - name: MYSQL_PASSWORD
            value: user
          - name: MYSQL_ROOT_PASSWORD
            value: root
          - name: MYSQL_USER
            value: user
          image: "docksal/db:1.1-mysql-5.6"
          name: db
          ports:
          - containerPort: 3306
          resources: {}
          volumeMounts:
          - mountPath: /var/www
            name: $SITE_NAME-db-data
        restartPolicy: Always
        volumes:
        - name: $SITE_NAME-db-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-db-data
  status: {}
kind: List
metadata: {}