apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: cli
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: cli
      spec:
        containers:
        - image: "docksal/cli:1.3-php7"
          name: cli
          env:
          - name: DOCROOT
            value: docroot
          - name: HOST_GID
            value: '1000'
          - name: HOST_UID
            value: '1000'
          resources: {}
          volumeMounts:
          - mountPath: /var/www
            name: $SITE_NAME-cli-data

        restartPolicy: Always
        volumes:
        - name: $SITE_NAME-cli-data
          persistentVolumeClaim:
            claimName: $SITE_NAME-cli-data
  status: {}
kind: List
metadata: {}