apiVersion: v1
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nvbenfs
      labels:
        io.kompose.service: web
      name: web
    spec:
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteMany
      nfs:
        server: 35.226.108.251
        path: "/web"
kind: List
metadata: {}