apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: db
    name: db
  spec:
    clusterIP: None
    ports:
    - name: headless
      port: 3306
      targetPort: 0
    selector:
      io.kompose.service: db
  status:
    loadBalancer: {}
kind: List
metadata: {}