apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: web
    name: web
  spec:
    externalTrafficPolicy: Cluster
    ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    selector:
      io.kompose.service: web
    type: LoadBalancer
  status:
    loadBalancer: {}
kind: List
metadata: {}