kind: Service
apiVersion: v1
metadata:
  name: nfs-shared1-server
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
    - name: mountd
      port: 20048
      targetPort: 20048
    - name: rpcbind
      port: 111
      targetPort: 111
  type: LoadBalancer
  selector:
    role: nfs-shared1-server